added fceux and tmux configs, OMP env, fix scripts

diff --git a/bin/check_symlinks b/bin/check_symlinks
--- a/bin/check_symlinks
+++ b/bin/check_symlinks
@@ -11,8 +11,8 @@ usage()
     echo "Hidden directories and files are searched."
     echo
     echo "These directories are ignored by default:"
-    for prune_dir in "$@"; do 
-        echo " $prune_dir"
+    for each in "$@"; do 
+        echo " $each"
     done
     echo
 }
@@ -20,30 +20,28 @@ usage()
 # Default options
 search_path="."
 recursive=0
-
-# Directory names to ignore
-declare -ra prune_dirs=("help" "icons" "doc" "man")
+prune_dirs=("help" "icons" "doc" "man") # directory names to ignore
 
 # Get command line options 
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage ${prune_dirs[@]}
-        exit 0
-        ;;
+            usage ${prune_dirs[@]}
+            exit 0
+            ;;
         -r | --recursive)
-        recursive=1
-        shift 1
-        ;;
+            recursive=1
+            shift
+            ;;
         -p | --path)
-        search_path="$2"
-        shift 2
-        ;;
+            search_path="$2"
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage ${prune_dirs[@]}
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage ${prune_dirs[@]}
+            exit 1
+            ;;
     esac
 done
 
@@ -58,16 +56,15 @@ prune_cmd=
 if [ ${#prune_dirs[@]} -gt 0 ]; then
     prune_cmd="-type d ("
     cnt=0
-    for d in "${prune_dirs[@]}"; do
+    for each in "${prune_dirs[@]}"; do
         if [ $cnt -eq 0 ]; then
-            prune_cmd+=" -name $d "
+            prune_cmd+=" -name $each "
         else
-            prune_cmd+="-o -name $d "
+            prune_cmd+="-o -name $each "
         fi
         cnt=$((cnt + 1))
     done
     prune_cmd+=") -prune -o"
-    unset cnt
 fi
 
 # Run
@@ -82,6 +79,5 @@ if [ ${#symlinks[@]} -gt 0 ]; then
     echo "Dangling symbolic links: ${#symlinks[@]}"
 fi
 
-unset recursive search_path symlinks prune_cmd
 exit 0
 
diff --git a/bin/click_applet b/bin/click_applet
--- a/bin/click_applet
+++ b/bin/click_applet
@@ -8,9 +8,9 @@ usage()
     echo "Perform a mouse click to an applet found in desktop panel."
     echo
     echo "Mouse click IDs:"
-    echo " 1 - left button (default)"
-    echo " 2 - middle button"
-    echo " 3 - right button"
+    echo " *1 - left button"
+    echo "  2 - middle button"
+    echo "  3 - right button"
     echo
 }
 
@@ -22,22 +22,22 @@ click_id=1
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -c | --click)
-        click_id=$2
-        shift 2 
-        ;;
+            click_id=$2
+            shift 2 
+            ;;
         -a | --applet)
-        applet="$2"
-        shift 2 
-        ;;
+            applet="$2"
+            shift 2 
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
@@ -56,37 +56,35 @@ fi
 # Save initial mouse position and active window
 # Outputs: X, Y, SCREEN, WINDOW
 eval $(xdotool getmouselocation --shell)
-declare -r win_active=$(xdotool getactivewindow)
+win_active=$(xdotool getactivewindow)
 
 # Query applet information
-declare -r applet_query="$(xwininfo -root -tree | grep $applet | head -n 1)"
+applet_query="$(xwininfo -root -tree | grep $applet | head -n 1)"
 if [ -z "$applet_query" ]; then
     echo "Error: applet \"$applet\" was not found in desktop panel."
     exit 1 
 fi
 
 # Get dimensions and position of applet 
-declare -ar applet_dims=($(echo "$applet_query" | awk '{ print $(NF-1) }' | sed 's/\([[:digit:]]\+\)x\([[:digit:]]\+\).*/\1 \2/g')) 
-declare -ar applet_pos=($(echo "$applet_query" | awk '{ print $NF }' | sed -e 's/+/ /g' -e 's/-/ -/g')) 
+applet_dims=($(echo "$applet_query" | awk '{ print $(NF-1) }' | sed 's/\([[:digit:]]\+\)x\([[:digit:]]\+\).*/\1 \2/g')) 
+applet_pos=($(echo "$applet_query" | awk '{ print $NF }' | sed -e 's/+/ /g' -e 's/-/ -/g')) 
 
 # Show panel bar
 x=$((applet_pos[0] + applet_dims[0]/2))
 y=$((applet_pos[1] + applet_dims[1]))
-eval $(xdotool mousemove --sync -- $x $y)
+xdotool mousemove --sync -- $x $y
 sleep 0.5 # allow panel to appear
 
 # Move mouse on top of applet
 y=$((applet_pos[1] + applet_dims[1]/2))
-eval $(xdotool mousemove --sync -- $x $y)
+xdotool mousemove --sync -- $x $y
 
 # Click applet 
-eval $(xdotool click $click_id)
+xdotool click $click_id
 
 # Restore initial mouse position and active window
-#eval $(xdotool mousemove --sync -- $X $Y windowactivate $win_active)
-eval $(xdotool mousemove --sync -- $X $Y)
+#xdotool mousemove --sync -- $X $Y windowactivate $win_active
+xdotool mousemove --sync -- $X $Y
 
-unset X Y SCREEN WINDOW
-unset click_id applet x y
 exit 0
 
diff --git a/bin/compile_asciidoc b/bin/compile_asciidoc
--- a/bin/compile_asciidoc
+++ b/bin/compile_asciidoc
@@ -21,30 +21,30 @@ filext=".asciidoc"
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -a | --article)
-        adtype=0
-        shift 1
-        ;;
+            adtype=0
+            shift
+            ;;
         -b | --book)
-        adtype=1
-        shift 1
-        ;;
+            adtype=1
+            shift
+            ;;
         -d | --docbook)
-        adtype=2
-        shift 1
-        ;;
+            adtype=2
+            shift
+            ;;
         -f | --file)
-        adffile="$2"
-        shift 2
-        ;;
+            adffile="$2"
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
      
diff --git a/bin/compile_dot b/bin/compile_dot
--- a/bin/compile_dot
+++ b/bin/compile_dot
@@ -19,22 +19,22 @@ fdotfile=
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -t | --tex)
-        tex=1
-        shift 1
-        ;;
+            tex=1
+            shift
+            ;;
         -f | --file)
-        fdotfile="$2"
-        shift 2
-        ;;
+            fdotfile="$2"
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
@@ -81,6 +81,5 @@ fi
 # Change to initial directory
 popd
 
-unset tex fdotfile num_dotfiles dotfile base_dotfile dir_dotfile out_dotfile dot_cmd view_cmd
 exit 0
 
diff --git a/bin/compile_latex b/bin/compile_latex
--- a/bin/compile_latex
+++ b/bin/compile_latex
@@ -27,34 +27,34 @@ filext=".tex"
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -b | --bibtex)
-        bibtex=1
-        shift 1
-        ;;
+            bibtex=1
+            shift
+            ;;
         -c | --clean)
-        clean=1
-        shift 1
-        ;;
+            clean=1
+            shift
+            ;;
         -p | --pdfpc)
-        pdfpc=1
-        shift 1
-        ;;
+            pdfpc=1
+            shift
+            ;;
         -w | --workdir)
-        workdir="$2"
-        shift 2
-        ;;
+            workdir="$2"
+            shift 2
+            ;;
         -f | --file)
-        texffile="$2"
-        shift 2
-        ;;
+            texffile="$2"
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/flush_term b/bin/flush_term
--- a/bin/flush_term
+++ b/bin/flush_term
@@ -19,23 +19,23 @@ empty_rows=0
 while [ "$1" ]; do
     case "$1" in
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -r | --row)
-        empty_rows=$2
-        shift 2 
-        ;;
+            empty_rows=$2
+            shift 2 
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
 # Get terminal window maximum number of rows
-declare -r max_rows=$(tput lines)
+max_rows=$(tput lines)
 
 # Validate
 if [ $empty_rows -lt 0 ]; then
@@ -49,11 +49,12 @@ fi
 
 # Get current cursor row in terminal window
 . custom_utils
-declare -ra curr_pos=($(get_cursor_pos))
+curr_pos=($(get_cursor_pos))
 
 # Run
-[ $((max_rows - ${curr_pos[0]})) -le $empty_rows ] && clear
+if [ $((max_rows - ${curr_pos[0]})) -le $empty_rows ]; then
+    clear
+fi
 
-unset empty_rows
 exit 0
 
diff --git a/bin/matlab_cli b/bin/matlab_cli
--- a/bin/matlab_cli
+++ b/bin/matlab_cli
@@ -21,28 +21,28 @@ runcmd=
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -j | --jvm)
-        jvmcmd=
-        shift 1
-        ;;
+            jvmcmd=
+            shift
+            ;;
         -r | --run)
-        if [ "${2##*.}" = "m" ]; then
-            # Script
-            runcmd="-r \"try, run('$2'); catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end, exit(0);\""
-        else
-            # Command
-            runcmd="-r \"try, $2, catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end\""
-        fi
-        shift 2
-        ;;
+            if [ "${2##*.}" = "m" ]; then
+                # Script
+                runcmd="-r \"try, run('$2'); catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end, exit(0);\""
+            else
+                # Command
+                runcmd="-r \"try, $2, catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end\""
+            fi
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/monitor_change b/bin/monitor_change
--- a/bin/monitor_change
+++ b/bin/monitor_change
@@ -11,15 +11,15 @@ usage()
     echo "Direction ID is ignored if mirror option is set."
     echo
     echo "Protocols:"
-    echo " 0 -> LVDS (default)"
-    echo " 1 -> VGA"
-    echo " 2 -> HDMI"
+    echo " *0 -> LVDS"
+    echo "  1 -> VGA"
+    echo "  2 -> HDMI"
     echo
     echo "Direction IDs for extended mode:"
-    echo " 0 -> left (default)"
-    echo " 1 -> above"
-    echo " 2 -> right"
-    echo " 3 -> below"
+    echo " *0 -> left"
+    echo "  1 -> above"
+    echo "  2 -> right"
+    echo "  3 -> below"
     echo
 }
 
@@ -35,26 +35,26 @@ win_restore=0
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -m | --mirror)
-        mirror=1
-        shift 1
-        ;;
+            mirror=1
+            shift
+            ;;
         -p | --protocol)
-        mon_proto=$2
-        shift 2
-        ;;
+            mon_proto=$2
+            shift 2
+            ;;
         -d | --direction)
-        direction_id=$2
-        shift 2
-        ;;
+            direction_id=$2
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/mouse_teleport b/bin/mouse_teleport
--- a/bin/mouse_teleport
+++ b/bin/mouse_teleport
@@ -11,20 +11,21 @@ usage()
     echo "Also, left and right mouse clicks can be simulated (all other options are ignored)."
     echo
     echo "Screen IDs:"
-    echo " 0 -> current (default)"
-    echo " 1 -> lower-left"
-    echo " 2 -> second"
+    echo " *0 -> current"
+    echo "  1 -> lower-left"
+    echo "  2 -> second"
     echo
     echo "Direction IDs:"
-    echo " 0 -> left (default)"
-    echo " 1 -> up"
-    echo " 2 -> right"
-    echo " 3 -> down"
-    echo " 4 -> center (w/o relative flag)"
+    echo " *0 -> left"
+    echo "  1 -> up"
+    echo "  2 -> right"
+    echo "  3 -> down"
+    echo "  4 -> center (w/o relative flag)"
     echo
     echo "Click IDs:"
-    echo " 0 -> left (default)"
-    echo " 1 -> right"
+    echo " *0 -> left"
+    echo "  1 -> right"
+    echo
 }
 
 # Default options 
@@ -39,31 +40,31 @@ mouse_click=
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -r | --relative)
-        movement="mousemove_relative"
-        rel_dist=$2
-        shift 2
-        ;;
+            movement="mousemove_relative"
+            rel_dist=$2
+            shift 2
+            ;;
         -s | --screen)
-        screen_id=$2
-        shift 2
-        ;;
+            screen_id=$2
+            shift 2
+            ;;
         -d | --direction)
-        direction_id=$2
-        shift 2
-        ;;
+            direction_id=$2
+            shift 2
+            ;;
         -c | --click)
-        mouse_click=$2
-        shift 2
-        ;;
+            mouse_click=$2
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
@@ -96,10 +97,8 @@ if [ ! -z $mouse_click ]; then
     
     # Run
     case $mouse_click in
-        0) # left click
-        xdotool click 1 ;;
-        1) # right click
-        xdotool click 3 ;;
+        0) xdotool click 1 ;; # left click
+        1) xdotool click 3 ;; # right click
     esac
 else
     # Move mouse pointer
@@ -126,30 +125,30 @@ else
         # Move mouse to preset position 
         case $direction_id in
             0) # left
-            x=$edge_dist
-            y=$((screen_dims[1] / 2))
-            ;;
+                x=$edge_dist
+                y=$((screen_dims[1] / 2))
+                ;;
             1) # up
-            x=$((screen_dims[0] / 2))
-            y=$edge_dist
-            ;;
+                x=$((screen_dims[0] / 2))
+                y=$edge_dist
+                ;;
             2) # right 
-            x=$((screen_dims[0] - edge_dist))
-            y=$((screen_dims[1] / 2))
-            ;;
+                x=$((screen_dims[0] - edge_dist))
+                y=$((screen_dims[1] / 2))
+                ;;
             3) # down 
-            x=$((screen_dims[0] / 2))
-            if [ $screen_id -eq 1 ]; then
-                # Show desktop panel
-                y=${screen_dims[1]}
-            else
-                y=$((screen_dims[1] - edge_dist))
-            fi
-            ;;
+                x=$((screen_dims[0] / 2))
+                if [ $screen_id -eq 1 ]; then
+                    # Show desktop panel
+                    y=${screen_dims[1]}
+                else
+                    y=$((screen_dims[1] - edge_dist))
+                fi
+                ;;
             4) # center 
-            x=$((screen_dims[0] / 2))
-            y=$((screen_dims[1] / 2))
-            ;;
+                x=$((screen_dims[0] / 2))
+                y=$((screen_dims[1] / 2))
+                ;;
         esac
         x=$((screen_offs[0] + x))
         y=$((screen_offs[1] + y))
diff --git a/bin/nvidiax b/bin/nvidiax
--- a/bin/nvidiax
+++ b/bin/nvidiax
@@ -14,21 +14,20 @@ usage()
     echo "X11 NVIDIA configuration file: $1"
     echo
     echo "GPU Performance levels:"
-    echo " 1 -> high"
-    echo " 2 -> medium"
-    echo " 3 -> low (default)"
+    echo "  1 -> high"
+    echo "  2 -> medium"
+    echo " *3 -> low"
     echo
     echo "GPU launch tools:"
-    echo " 0 -> none"
-    echo " 1 -> primusrun (OpenGL support, default)"
-    echo " 2 -> optirun"
+    echo "  0 -> none"
+    echo " *1 -> primusrun (OpenGL support)"
+    echo "  2 -> optirun"
     echo
 }
 
-# X11 NVIDIA configuration file
-x11_nvidia_file="/etc/bumblebee/xorg.conf.nvidia"
 
 # Default options
+x11_nvidia_file="/etc/bumblebee/xorg.conf.nvidia" # X11 NVIDIA configuration file
 launch_tool=1
 perf_level=3
 perf_level_changed=0
@@ -38,26 +37,26 @@ app=
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage $x11_nvidia_file
-        exit 0
-        ;;
+            usage $x11_nvidia_file
+            exit 0
+            ;;
         -t | --tool)
-        launch_tool=$2
-        shift 2
-        ;;
+            launch_tool=$2
+            shift 2
+            ;;
         -p | --perf)
-        perf_level=$2
-        shift 2
-        ;;
+            perf_level=$2
+            shift 2
+            ;;
         -r | --run)
-        app="$2"
-        shift 2 
-        ;;
+            app="$2"
+            shift 2 
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage $x11_nvidia_file
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage $x11_nvidia_file
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/pause b/bin/pause
--- a/bin/pause
+++ b/bin/pause
@@ -13,14 +13,14 @@ usage()
 while [ "$1" ]; do
     case "$1" in
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/screen_cast b/bin/screen_cast
--- a/bin/screen_cast
+++ b/bin/screen_cast
@@ -15,13 +15,13 @@ usage()
     echo "Supported outfile formats: avi, mp4, mpg, mkv"
     echo
     echo "Video codecs:"
-    echo " libx264 (high) (default)"
-    echo " huffyuv (normal)"
-    echo " libxvid (low)"
+    echo " *libx264 (high)"
+    echo "  huffyuv (normal)"
+    echo "  libxvid (low)"
     echo
     echo "Screen IDs:"
-    echo " 0 -> lower-left (default)"
-    echo " 1 -> second"
+    echo " *0 -> lower-left"
+    echo "  1 -> second"
     echo
 }
 
@@ -39,42 +39,42 @@ outfile="$HOME/screencast_$(date +%m-%d-%Y_%H-%M).avi"
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -a | --audio)
-        use_audio=1
-        shift 1
-        ;;
+            use_audio=1
+            shift
+            ;;
         -w | --window)
-        use_window=1
-        shift 1
-        ;;
+            use_window=1
+            shift
+            ;;
         -t | --timer)
-        timer=$2
-        shift 2
-        ;;
+            timer=$2
+            shift 2
+            ;;
         -v | --vcodec)
-        vcodec="$2"
-        shift 2
-        ;;
+            vcodec="$2"
+            shift 2
+            ;;
         -r | --rate)
-        framerate=$2
-        shift 2
-        ;;
+            framerate=$2
+            shift 2
+            ;;
         -s | --screen)
-        screen_id=$2
-        shift 2
-        ;;
+            screen_id=$2
+            shift 2
+            ;;
         -o | --outfile)
-        outfile="$2"
-        shift 2
-        ;;
+            outfile="$2"
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/sound_change b/bin/sound_change
--- a/bin/sound_change
+++ b/bin/sound_change
@@ -11,11 +11,11 @@ usage()
     echo "Default is ALSA PCI card with output analog stereo profile."
     echo
     echo "Profiles:"
-    echo " 0 -> off"
-    echo " 1 -> analog stereo (default)"
-    echo " 2 -> HDMI stereo"
-    echo " 3 -> HDMI surround"
-    echo " 4 -> HDMI surround 7.1"
+    echo "  0 -> off"
+    echo " *1 -> analog stereo"
+    echo "  2 -> HDMI stereo"
+    echo "  3 -> HDMI surround"
+    echo "  4 -> HDMI surround 7.1"
     echo
 }
 
@@ -28,22 +28,22 @@ profile_id=1
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage
-        exit 0
-        ;;
+            usage
+            exit 0
+            ;;
         -i | --input)
-        sound_input=1
-        shift 1
-        ;;
+            sound_input=1
+            shift 1
+            ;;
         -p | --profile)
-        profile_id=$2
-        shift 2
-        ;;
+            profile_id=$2
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+            ;;
     esac
 done
 
diff --git a/bin/wallpaper_change b/bin/wallpaper_change
--- a/bin/wallpaper_change
+++ b/bin/wallpaper_change
@@ -9,11 +9,11 @@ usage()
     echo
     echo "Wallpaper IDs:"
     local wid=0
-    for wfile in "$@"; do 
+    for each in "$@"; do 
         if [ $wid -eq 0 ]; then
-            echo " $wid -> $wfile (default)"
+            echo " *$wid -> $each"
         else
-            echo " $wid -> $wfile"
+            echo "  $wid -> $each"
         fi
         wid=$((wid + 1))
     done
@@ -33,18 +33,18 @@ wallfiles=(
 while [ "$1" ]; do 
     case "$1" in 
         -h | --help)
-        usage ${wallfiles[@]}
-        exit 0
-        ;;
+            usage ${wallfiles[@]}
+            exit 0
+            ;;
         -w | --wallpaper)
-        wallid=$2
-        shift 2
-        ;;
+            wallid=$2
+            shift 2
+            ;;
         *)
-        echo "Error: invalid command line option, $1"
-        usage ${wallfiles[@]}
-        exit 1
-        ;;
+            echo "Error: invalid command line option, $1"
+            usage ${wallfiles[@]}
+            exit 1
+            ;;
     esac
 done
 
