made some scripts POSIX-compliant

diff --git a/bin/clear_after b/bin/clear_after
--- a/bin/clear_after
+++ b/bin/clear_after
@@ -1,47 +1,44 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
 cat << _EOF_
-Usage: $(basename $0) [--help] "APPLICATION"
+Usage: $(basename $0) [--help] "APPLICATION" "ARGS"
 
 Wrapper to invoke an application and clear terminal after its completion.
 _EOF_
 }
 
 # Default options
-app=
+app=""
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        *)
-            app="$@"
-            shift $#
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        *) app="$@"
+            shift $# ;;
     esac
 done
 
 # Validate
 if [ -z "$app" ]; then
-    error_msg "no application was specified" 1
+    echo -e "$errmsg: no application was specified"
+    exit 1
 fi
 
-# app [args]
-appname="$(echo "$app" | sed 's/\b\w\+=\S*\s\b//' | awk '{ print $1 }')"
-if [ ! "$(command -v $appname)" ]; then
-    error_msg "application '$appname' was not found" 1
+# [ENV_VAR=value] app [args]
+appname="$(echo "$app" | sed 's/\b\w\+=\S*\s\b//g' | awk '{ print $1 }')"
+if [ ! "$(command -v "$appname")" ] && [ ! -x "$appname" ]; then
+    echo -e "$errmsg: application '$appname' was not found"
+    exit 1
 fi
 
 # Run
-$app
+eval $app
 tput clear
-
-exit 0
 
diff --git a/bin/compile_asciidoc b/bin/compile_asciidoc
--- a/bin/compile_asciidoc
+++ b/bin/compile_asciidoc
@@ -1,7 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
 . "$HOME/bin/common_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
@@ -22,39 +23,33 @@ _EOF_
 
 # Default options
 adtype=0
-adffile=
+adffile=""
 filext=".asciidoc"
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -t | --type)
-            adtype=$2
-            shift 2
-            ;;
-        -f | --file)
-            adffile="$2"
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -t | --type) adtype=$2
+            shift 2 ;;
+        -f | --file) adffile="$2"
+            shift 2 ;;
+        *) usage
+            echo -e "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Validate
-if [ -z "$adffile" ]; then
-    find_file_ext "$filext"
-    [ $? -eq 0 ] || exit 1
-    adffile="$file_list"
+if [ $adtype -lt 0 ] || [ $adtype -gt 2 ]; then
+    echo -e "$errmsg: invalid document type value"
+    exit 1
 fi
-if [ ! -e "$adffile" ]; then
-    error_msg "file '$adffile' does not exists" 1
+[ -z "$adffile" ] && adffile="$(find_file_ext "$filext")"
+if [ ! -f "$adffile" ]; then
+    echo -e "$errmsg: file '$adffile' does not exists"
+    exit 1
 fi
 
 # Commands (compile and view)
@@ -63,12 +58,12 @@ adfile="$(basename "$adffile")"
 adbase="${adfile%.*}"
 adpdf="$adbase.pdf"
 adxml="$adbase.xml"
-dblatex_cmd="dblatex $adxml -T simple"
-view_cmd="evince"
+dblatex_cmd="dblatex \"$adxml\" -T simple"
+view_cmd="evince \"$adpdf\""
 case $adtype in
-    0) ad_cmd="a2x -d article -f pdf $adfile" ;;
-    1) ad_cmd="a2x -d book -f pdf $adfile" ;;
-    2) ad_cmd="asciidoc -b docbook $adfile" ;;
+    0) ad_cmd="a2x -d article -f pdf \"$adfile\"" ;;
+    1) ad_cmd="a2x -d book -f pdf \"$adfile\"" ;;
+    2) ad_cmd="asciidoc -b docbook \"$adfile\"" ;;
 esac
 
 # Change to file directory
@@ -76,17 +71,15 @@ pushd . > /dev/null 2>&1
 cd "$addir"
 
 # Run
-$ad_cmd
-if [ -e "$adxml" ]; then
-    $dblatex_cmd
+eval $ad_cmd; [ $? -eq 0 ] || exit 1
+if [ -f "$adxml" ]; then
+    eval $dblatex_cmd; [ $? -eq 0 ] || exit 1
     rm "$adxml"
 fi
 
 # View
-[ -e "$adpdf" ] && $view_cmd "$adpdf" &
+[ -f "$adpdf" ] && eval $view_cmd &
 
 # Change to initial directory
 popd > /dev/null 2>&1
-
-exit 0
 
diff --git a/bin/compile_dot b/bin/compile_dot
--- a/bin/compile_dot
+++ b/bin/compile_dot
@@ -1,12 +1,13 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
 . "$HOME/bin/common_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
 cat << _EOF_
-Usage: $(basename $0) [--help] [--tex] [--file="DOTFILE"]
+Usage: $(basename $0) [--help] [--tex] [--file "DOTFILE"]
 
 Compile a DOT file into PNG or TeX format.
 If a DOT file is not provided, current directory is search for one.
@@ -16,39 +17,29 @@ _EOF_
 
 # Default options
 tex=0
-dotffile=
+dotffile=""
 filext=".dot"
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -t | --tex)
-            tex=1
-            shift
-            ;;
-        -f | --file)
-            dotffile="$2"
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -t | --tex) tex=1
+            shift ;;
+        -f | --file) dotffile="$2"
+            shift 2 ;;
+        *) usage
+            echo -e "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Validate
-if [ -z "$dotffile" ]; then
-    find_file_ext "$filext"
-    [ $? -eq 0 ] || exit 1
-    dotffile="$file_list"
-fi
-if [ ! -e "$dotffile" ]; then
-    error_msg "file '$dotffile' does not exists" 1
+[ -z "$dotffile" ] && dotffile="$(find_file_ext "$filext")"
+if [ ! -f "$dotffile" ]; then
+    echo -e "$errmsg: file '$dotffile' does not exists"
+    exit 1
 fi
 
 # Commands (compile and view)
@@ -57,10 +48,10 @@ dotfile="$(basename "$dotffile")"
 dotbase="${dotfile%.*}"
 dotpng="$dotbase.png"
 dottex="$dotbase.tex"
-view_cmd="gpicview"
+view_cmd="gpicview \"$dotpng\""
 case $tex in
-    0) dot_cmd="dot -Tpng $dotfile -o $dotpng" ;;
-    1) dot_cmd="dot -Txdot $dotfile | dot2tex > $dottex" ;;
+    0) dot_cmd="dot -Tpng \"$dotfile\" -o \"$dotpng\"" ;;
+    1) dot_cmd="dot -Txdot \"$dotfile\" | dot2tex > \"$dottex\"" ;;
 esac
 
 # Change to file directory
@@ -68,13 +59,11 @@ pushd . > /dev/null 2>&1
 cd "$dotdir"
 
 # Run
-$dot_cmd
+eval $dot_cmd; [ $? -eq 0 ] || exit 1
 
 # View
-[ -e "$dotpng" ] && $view_cmd "$dotpng" &
+[ -f "$dotpng" ] && eval $view_cmd &
 
 # Change to initial directory
 popd > /dev/null 2>&1
-
-exit 0
 
diff --git a/bin/compile_latex b/bin/compile_latex
--- a/bin/compile_latex
+++ b/bin/compile_latex
@@ -1,7 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
 . "$HOME/bin/common_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
@@ -23,51 +24,35 @@ bibtex=0
 clean=0
 pdfpc=0
 workdir="build"
-texffile=
+texffile=""
 filext=".tex"
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -b | --bibtex)
-            bibtex=1
-            shift
-            ;;
-        -c | --clean)
-            clean=1
-            shift
-            ;;
-        -p | --pdfpc)
-            pdfpc=1
-            shift
-            ;;
-        -w | --workdir)
-            workdir="$2"
-            shift 2
-            ;;
-        -f | --file)
-            texffile="$2"
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -b | --bibtex) bibtex=1
+            shift ;;
+        -c | --clean) clean=1
+            shift ;;
+        -p | --pdfpc) pdfpc=1
+            shift ;;
+        -w | --workdir) workdir="$2"
+            shift 2 ;;
+        -f | --file) texffile="$2"
+            shift 2 ;;
+        *) usage
+            echo -e "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Validate
-if [ -z "$texffile" ]; then
-    find_file_ext "$filext"
-    [ $? -eq 0 ] || exit 1
-    texffile="$file_list"
-fi
-if [ ! -e "$texffile" ]; then
-    error_msg "file '$texffile' does not exists" 1
+[ -z "$texffile" ] && texffile="$(find_file_ext "$filext")"
+if [ ! -f "$texffile" ]; then
+    echo -e "$errmsg: file '$texffile' does not exists"
+    exit 1
 fi
 
 # Commands (compile and view)
@@ -75,11 +60,11 @@ texdir="$(dirname "$texffile")"
 texfile="$(basename "$texffile")"
 texbase="${texfile%.*}"
 texpdf="$texbase.pdf"
-pdflatex_cmd="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=$workdir $texfile"
-bibtex_cmd="bibtex $workdir/$texbase"
+pdflatex_cmd="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=\"$workdir\" \"$texfile\""
+bibtex_cmd="bibtex \"$workdir/$texbase\""
 case $pdfpc in
-    0) view_cmd="evince" ;;
-    *) view_cmd="pdfpc" ;;
+    0) view_cmd="evince \"$workdir/$texpdf\"" ;;
+    1) view_cmd="pdfpc \"$workdir/$texpdf\"" ;;
 esac
 
 # Change to file directory
@@ -89,18 +74,16 @@ cd "$texdir"
 [ ! -d "$workdir" ] && mkdir "$workdir"
 
 # Run
-$pdflatex_cmd
-[ $? -eq 0 ] || exit 1
+eval $pdflatex_cmd; [ $? -eq 0 ] || exit 1
 if [ $bibtex -ge 1 ]; then
-    $bibtex_cmd
-    $pdflatex_cmd
+    eval $bibtex_cmd; [ $? -eq 0 ] || exit 1
+    eval $pdflatex_cmd; [ $? -eq 0 ] || exit 1
 fi
-$pdflatex_cmd
+eval $pdflatex_cmd; [ $? -eq 0 ] || exit 1
 
 # Clean and view
 if [ $clean -eq 0 ]; then
-    texpdf="$workdir/$texpdf"
-    [ -e "$texpdf" ] && $view_cmd "$texpdf" &
+    [ -f "$workdir/$texpdf" ] && eval $view_cmd &
 else
     mv "$workdir/$texpdf" "$texpdf"
     rm -r "$workdir"
@@ -108,6 +91,4 @@ fi
 
 # Change to initial directory
 popd > /dev/null 2>&1
-
-exit 0
 
diff --git a/bin/compile_ps b/bin/compile_ps
--- a/bin/compile_ps
+++ b/bin/compile_ps
@@ -1,7 +1,8 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
 . "$HOME/bin/common_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
@@ -15,35 +16,27 @@ _EOF_
 }
 
 # Default options
-psffile=
+psffile=""
 filext=".ps"
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -f | --file)
-            psffile="$2"
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -f | --file) psffile="$2"
+            shift 2 ;;
+        *) usage
+            echo -e "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Validate
-if [ -z "$psffile" ]; then
-    find_file_ext "$filext"
-    [ $? -eq 0 ] || exit 1
-    psffile="$file_list"
-fi
-if [ ! -e "$psffile" ]; then
-    error_msg "file '$psffile' does not exists" 1
+[ -z "$psffile" ] && psffile="$(find_file_ext "$filext")"
+if [ ! -f "$psffile" ]; then
+    echo -e "$errmsg: file '$psffile' does not exists"
+    exit 1
 fi
 
 # Commands (compile and view)
@@ -52,22 +45,22 @@ psfile="$(basename "$psffile")"
 psbase="${psfile%.*}"
 pspdf="$psbase.pdf"
 pseps="$psbase.eps"
-view_cmd="evince"
+ps1_cmd="ps2eps --force --ignoreBB --rotate=+ \"$psfile\""
+ps2_cmd="epstopdf --outfile=\"$pspdf\" \"$pseps\""
+view_cmd="evince \"$pspdf\""
 
 # Change to file directory
 pushd . > /dev/null 2>&1
 cd "$psdir"
 
 # Run
-ps2eps --force --ignoreBB --rotate=+ "$psfile"
-epstopdf --outfile="$pspdf" "$pseps"
+eval $ps1_cmd; [ $? -eq 0 ] || exit 1
+eval $ps2_cmd; [ $? -eq 0 ] || exit 1
 rm "$pseps"
 
 # View
-[ -e "$pspdf" ] && $view_cmd "$pspdf" &
+[ -f "$pspdf" ] && eval $view_cmd &
 
 # Change to initial directory
 popd > /dev/null 2>&1
-
-exit 0
 
diff --git a/bin/sound_change b/bin/sound_change
--- a/bin/sound_change
+++ b/bin/sound_change
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
@@ -29,28 +30,22 @@ profile_id=1
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -i | --input)
-            sound_input=1
-            shift 1
-            ;;
-        -p | --profile)
-            profile_id=$2
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -i | --input) sound_input=1
+            shift ;;
+        -p | --profile) profile_id=$2
+            shift 2 ;;
+        *) usage
+            echo -e "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Validate
 if [ $profile_id -lt 0 ] && [ $profile_id -gt 4 ]; then
-    error_msg "invalid output profile value" 1
+    echo -e "$errmsg: invalid output profile value"
+    exit 1
 fi
 
 # Select sound output profile
@@ -73,12 +68,8 @@ else
     profile="output:$new_sink"
 
     # Check for sound input profile
-    if [ $sound_input -eq 1 ]; then
-        profile+="+input:analog-stereo"
-    fi
+    [ $sound_input -eq 1 ] && profile="${profile}+input:analog-stereo"
 fi
 
 pacmd set-card-profile "$sound_card" "$profile"
-
-exit 0
 
