added dependence app checks and more POSIX changes

diff --git a/bin/click_applet b/bin/click_applet
--- a/bin/click_applet
+++ b/bin/click_applet
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 errmsg="\033[01;31mERROR\033[00m"
 warnmsg="\033[01;33mWARNING\033[00m"
@@ -6,11 +6,13 @@ warnmsg="\033[01;33mWARNING\033[00m"
 usage()
 {
 cat << _USAGE_
-Usage: $(basename $0) [--help] [--click CLICK_ID] --applet "APPLET"
+Usage: $(basename $0) [--help] [--click CLICK_ID] [--delay CLICK_DELAY] --applet "APPLET"
 
-Perform a mouse click to an applet found in desktop panel.
+Perform a mouse click/hover to an applet found in desktop panel.
+Default click/hover delay is 1 seconds.
 
 Mouse click IDs:
+  0 - no click
  *1 - left button
   2 - middle button
   3 - right button
@@ -20,6 +22,7 @@ _USAGE_
 # Default options
 applet=""
 click_id=1
+click_delay=1
 
 # Get command line options
 while [ "$1" ]; do
@@ -27,6 +30,8 @@ while [ "$1" ]; do
         -h | --help) usage
             exit 0 ;;
         -c | --click) click_id=$2
+            shift 2 ;;
+        -d | --delay) click_delay=$2
             shift 2 ;;
         -a | --applet) applet="$2"
             shift 2 ;;
@@ -36,14 +41,27 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in xdotool xwininfo; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
-if [ -z "$applet" ]; then
-    printf "%b\n" "$errmsg: no applet was specified"
+if [ $click_id -lt 0 ] || [ $click_id -gt 3 ]; then
+    printf "%b\n" "$errmsg: invalid mouse click value [0-3]"
     exit 1
 fi
-
-if [ $click_id -lt 1 ] || [ $click_id -gt 3 ]; then
-    printf "%b\n" "$errmsg: invalid 'mouse click' value [1-3]"
+if [ $click_delay -lt 0 ] || [ $click_delay -gt 30 ]; then
+    printf "%b\n" "$errmsg: invalid delay value [0-30]"
+    exit 1
+fi
+if [ -z "$applet" ]; then
+    printf "%b\n" "$errmsg: no applet was specified"
     exit 1
 fi
 
@@ -53,33 +71,35 @@ eval $(xdotool getmouselocation --shell)
 win_active=$(xdotool getactivewindow)
 
 # Query applet information
-applet_query="$(xwininfo -root -tree | grep $applet | head -n 1)"
+applet_query="$(xwininfo -root -tree | grep -i "$applet" | head -n 1)"
 if [ -z "$applet_query" ]; then
     printf "%b\n" "$errmsg: applet '$applet' was not found in desktop panel"
     exit 1
 fi
 
 # Get dimensions and position of applet
-applet_dims=($(echo "$applet_query" | awk '{ print $(NF-1) }' | sed 's/\([[:digit:]]\+\)x\([[:digit:]]\+\).*/\1 \2/g'))
-applet_pos=($(echo "$applet_query" | awk '{ print $NF }' | sed -e 's/+/ /g' -e 's/-/ -/g'))
+applet_dims="$(printf "$applet_query" | awk '{ print $(NF-1) }' | sed 's/\([[:digit:]]\+\)x\([[:digit:]]\+\).*/\1,\2/g')"
+applet_pos="$(printf "$applet_query" | awk '{ print $NF }' | sed -e 's/+/,/g' -e 's/-/,-/g' | cut --complement -c 1)"
+applet_dims0=$(printf "$applet_dims" | cut -d ',' -f 1)
+applet_dims1=$(printf "$applet_dims" | cut -d ',' -f 2)
+applet_pos0=$(printf "$applet_pos" | cut -d ',' -f 1)
+applet_pos1=$(printf "$applet_pos" | cut -d ',' -f 2)
 
 # Show panel bar
-x=$((applet_pos[0] + applet_dims[0]/2))
-y=$((applet_pos[1] + applet_dims[1]))
+x=$((applet_pos0 + applet_dims0/2))
+y=$((applet_pos1 + applet_dims1))
 xdotool mousemove --sync -- $x $y
-sleep 1 # allow panel to appear
+sleep 1 # allow panel to appear, if hidden
 
-# Move mouse on top of applet
-y=$((applet_pos[1] + applet_dims[1]/2))
+# Move mouse on top of applet icon
+y=$((applet_pos1 + applet_dims1/2))
 xdotool mousemove --sync -- $x $y
-sleep 0.5 # wait for app detection
+sleep $click_delay # wait for applet detection
 
 # Click applet
-xdotool click $click_id
+[ $click_id -gt 0 ] && xdotool click $click_id
 
 # Restore initial mouse position and active window
 #xdotool mousemove --sync -- $X $Y windowactivate $win_active
 xdotool mousemove --sync -- $X $Y
-
-exit 0
 
diff --git a/bin/compile_asciidoc b/bin/compile_asciidoc
--- a/bin/compile_asciidoc
+++ b/bin/compile_asciidoc
@@ -41,6 +41,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in asciidoc a2x dblatex xdg-open; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 if [ $adtype -lt 0 ] || [ $adtype -gt 2 ]; then
     printf "%b\n" "$errmsg: invalid document type value"
@@ -59,7 +69,7 @@ adbase="${adfile%.*}"
 adpdf="$adbase.pdf"
 adxml="$adbase.xml"
 dblatex_cmd="dblatex \"$adxml\" -T simple"
-view_cmd="evince \"$adpdf\""
+view_cmd="xdg-open \"$adpdf\""
 case $adtype in
     0) ad_cmd="a2x -d article -f pdf \"$adfile\"" ;;
     1) ad_cmd="a2x -d book -f pdf \"$adfile\"" ;;
diff --git a/bin/compile_dot b/bin/compile_dot
--- a/bin/compile_dot
+++ b/bin/compile_dot
@@ -35,6 +35,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in dot xdg-open; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 [ -z "$dotffile" ] && dotffile="$(find_file_ext "$filext")"
 if [ ! -f "$dotffile" ]; then
@@ -48,7 +58,7 @@ dotfile="$(basename "$dotffile")"
 dotbase="${dotfile%.*}"
 dotpng="$dotbase.png"
 dottex="$dotbase.tex"
-view_cmd="gpicview \"$dotpng\""
+view_cmd="xdg-open \"$dotpng\""
 case $tex in
     0) dot_cmd="dot -Tpng \"$dotfile\" -o \"$dotpng\"" ;;
     1) dot_cmd="dot -Txdot \"$dotfile\" | dot2tex > \"$dottex\"" ;;
diff --git a/bin/compile_latex b/bin/compile_latex
--- a/bin/compile_latex
+++ b/bin/compile_latex
@@ -48,6 +48,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in pdflatex bibtex pdfpc xdg-open; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 [ -z "$texffile" ] && texffile="$(find_file_ext "$filext")"
 if [ ! -f "$texffile" ]; then
@@ -63,7 +73,7 @@ texpdf="$texbase.pdf"
 pdflatex_cmd="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=\"$workdir\" \"$texfile\""
 bibtex_cmd="bibtex \"$workdir/$texbase\""
 case $pdfpc in
-    0) view_cmd="evince \"$workdir/$texpdf\"" ;;
+    0) view_cmd="xdg-open \"$workdir/$texpdf\"" ;;
     1) view_cmd="pdfpc \"$workdir/$texpdf\"" ;;
 esac
 
diff --git a/bin/compile_ps b/bin/compile_ps
--- a/bin/compile_ps
+++ b/bin/compile_ps
@@ -32,6 +32,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in ps2eps epstopdf xdg-open; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 [ -z "$psffile" ] && psffile="$(find_file_ext "$filext")"
 if [ ! -f "$psffile" ]; then
@@ -47,7 +57,7 @@ pspdf="$psbase.pdf"
 pseps="$psbase.eps"
 ps1_cmd="ps2eps --force --ignoreBB --rotate=+ \"$psfile\""
 ps2_cmd="epstopdf --outfile=\"$pspdf\" \"$pseps\""
-view_cmd="evince \"$pspdf\""
+view_cmd="xdg-open \"$pspdf\""
 
 # Change to file directory
 pushd . > /dev/null 2>&1
@@ -56,7 +66,7 @@ cd "$psdir"
 # Run
 eval $ps1_cmd; [ $? -eq 0 ] || exit 1
 eval $ps2_cmd; [ $? -eq 0 ] || exit 1
-rm "$pseps"
+[ -f "$pseps" ] && rm "$pseps"
 
 # View
 [ -f "$pspdf" ] && eval $view_cmd &
diff --git a/bin/compile_sas b/bin/compile_sas
--- a/bin/compile_sas
+++ b/bin/compile_sas
@@ -33,6 +33,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in sas; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 [ -z "$sasffile" ] && sasffile="$(find_file_ext "$filext")"
 if [ ! -f "$sasffile" ]; then
diff --git a/bin/matlab_cli b/bin/matlab_cli
--- a/bin/matlab_cli
+++ b/bin/matlab_cli
@@ -42,6 +42,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in matlab; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Run
 matlab_cmd="matlab $deskcmd $jvmcmd $runcmd"
 eval $matlab_cmd; [ $? -eq 0 ] || exit 1
diff --git a/bin/pause b/bin/pause
--- a/bin/pause
+++ b/bin/pause
@@ -14,7 +14,9 @@ while [ "$1" ]; do
     case "$1" in
         -h | --help) usage
             exit 0 ;;
-        *) shift ;;
+        *) usage
+            printf "%b\n" "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
@@ -22,11 +24,9 @@ done
 ukey=""
 read -r -n 1 -p 'Press any key to continue ... ' ukey
 
-dkey=$(printf "$ukey" | od -An -t uC | awk '{ print $1 }')
-[ -z "$dkey" ] && dkey=0
-
-# Print newline if pressed key is not '\n' or '\r'
-if [ $dkey -ne 10 ] && [ $dkey -ne 13 ]; then
+#dkey=$(printf "$ukey" | od -An -t uC | cut -f 1)
+# Print newline if pressed key is not '\r\n'
+#if [ $dkey -ne 10 ] && [ $dkey -ne 13 ]; then
     printf '\n'
-fi
+#fi
 
diff --git a/bin/sound_change b/bin/sound_change
--- a/bin/sound_change
+++ b/bin/sound_change
@@ -42,6 +42,16 @@ while [ "$1" ]; do
     esac
 done
 
+# Check application dependences
+missing_apps=0
+for a in pacmd; do
+    if [ ! "$(command -v "$a")" ]; then
+        printf "%b\n" "$errmsg: application '$a' was not found"
+        missing_apps=$((missing_apps + 1))
+    fi
+done
+[ $missing_apps -eq 0 ] || exit 1
+
 # Validate
 if [ $profile_id -lt 0 ] && [ $profile_id -gt 4 ]; then
     printf "%b\n" "$errmsg: invalid output profile value"
