improved scripts (structure and eval)

diff --git a/bin/compile_asciidoc b/bin/compile_asciidoc
--- a/bin/compile_asciidoc
+++ b/bin/compile_asciidoc
@@ -6,18 +6,16 @@ usage()
     echo "Usage: $(basename $0) [--help] [--article] [--book] [--docbook] [--file \"ADFILE\"]"
     echo
     echo "Compile an ASCIIDoc file into PDF format."
-    echo "If an ASCIIDoc file is not provided, current directory is searched for one."
     echo
-    echo "Type of output file:"
-    echo " 0 -> article (default)"
-    echo " 1 -> book"
-    echo " 2 -> docbook"
+    echo "If an ASCIIDoc file is not provided, current directory is searched for one."
+    echo "Default file type is article."
     echo
 }
 
 # Default options
-type_id=0
-fadfile=
+adtype=0
+adffile=
+filext=".asciidoc"
 
 # Get command line options 
 while [ "$1" ]; do 
@@ -27,19 +25,19 @@ while [ "$1" ]; do
         exit 0
         ;;
         -a | --article)
-        type_id=0
+        adtype=0
         shift 1
         ;;
         -b | --book)
-        type_id=1
+        adtype=1
         shift 1
         ;;
         -d | --docbook)
-        type_id=2
+        adtype=2
         shift 1
         ;;
         -f | --file)
-        fadfile="$2"
+        adffile="$2"
         shift 2
         ;;
         *)
@@ -51,62 +49,49 @@ while [ "$1" ]; do
 done
      
 # Validate
-if [ $type_id -lt 0 ] || [ $type_id -gt 2 ]; then
-    echo "Error: invalid value for compilation type."
-    exit 1
-fi
-
-if [ -z "$fadfile" ]; then
-    fadfile="$(ls | grep '.*\.asciidoc$')"
-    num_adfiles=$(echo -n "$fadfile" | wc -l)
-    if [ $num_adfiles -eq 1 ]; then
-        echo "Automatic ASCIIDoc file found, '$fadfile'."
-    elif [ $num_adfiles -le 0 ]; then
-        echo "Error: no automatic ASCIIDoc file found."
-        exit 1
-    elif [ $num_adfiles -gt 1 ]; then
-        echo "Error: too many ASCIIDoc files found, '$fadfile'."
-        exit 1
-    fi
-elif [ ! -e "$fadfile" ]; then
-    echo "Error: ASCIIDoc file '$fadfile' does not exists."
+if [ -z "$adffile" ]; then
+    . common_utils
+    find_file_ext "$filext" 
+    [ $? -ne 0 ] && exit 1
+    adffile="$file_list"
+elif [ ! -e "$adffile" ]; then
+    echo "Error: file '$adffile' does not exists."
     exit 1
 fi
 
 # Commands (compile and view)
-dir_adfile="$(dirname $fadfile)"
-adfile="$(basename $fadfile)"
-base_adfile="${adfile%.*}"
-pdf_adfile="$base_adfile.pdf"
-xml_adfile="$base_adfile.xml"
-dblatex_cmd="dblatex $xml_adfile -T simple"
-view_cmd="evince $pdf_adfile"
+addir="$(dirname $adffile)"
+adfile="$(basename $adffile)"
+adbase="${adfile%.*}"
+adpdf="$adbase.pdf"
+adxml="$adbase.xml"
+dblatex_cmd="dblatex $adxml -T simple"
+view_cmd="evince $adpdf"
 
-case $type_id in
+case $adtype in
     0) ad_cmd="a2x -d article -f pdf $adfile" ;;
     1) ad_cmd="a2x -d book -f pdf $adfile" ;;
     2) ad_cmd="asciidoc -b docbook $adfile" ;;
 esac
 
 # Change to file directory
-pushd .
-cd "$dir_adfile"
+pushd . > /dev/null 2>&1
+cd "$addir"
 
 # Run
-eval "$ad_cmd"
-if [ -e "$xml_adfile" ]; then
-    eval "$dblatex_cmd"
-    rm "$xml_adfile"
+$ad_cmd
+if [ -e "$adxml" ]; then
+    $dblatex_cmd
+    rm "$adxml"
 fi
 
 # View
-if [ -e "$pdf_adfile" ]; then
-    eval "$view_cmd & disown"
+if [ -e "$adpdf" ]; then
+    $view_cmd & disown
 fi
 
 # Change to initial directory
-popd
+popd > /dev/null 2>&1
 
-unset type_id fadfile num_adfiles adfile dir_adfile base_adfile pdf_adfile xml_adfile ad_cmd dblatex_cmd view_cmd
 exit 0
 
diff --git a/bin/compile_dot b/bin/compile_dot
--- a/bin/compile_dot
+++ b/bin/compile_dot
@@ -1,12 +1,86 @@
 #!/bin/bash
 
-DOTFILE=$1
+usage()
+{
+    echo
+    echo "Usage: $(basename $0) [--help] [--tex] --file=\"DOTFILE\""
+    echo
+    echo "Compile a DOT file into PNG or TeX format."
+    echo "If a DOT file is not provided, current directory is search for one."
+    echo "To generate TeX output format, enable 'tex' option."
+    echo
+}
 
-if [ ! -z $DOTFILE ]; then
-    dot -Tpng $DOTFILE -o graph.png
+# Default options
+tex=0
+fdotfile=
+
+# Get command line options
+while [ "$1" ]; do 
+    case "$1" in 
+        -h | --help)
+        usage
+        exit 0
+        ;;
+        -t | --tex)
+        tex=1
+        shift 1
+        ;;
+        -f | --file)
+        fdotfile="$2"
+        shift 2
+        ;;
+        *)
+        echo "Error: invalid command line option, $1"
+        usage
+        exit 1
+        ;;
+    esac
+done
+
+# Validate
+if [ -z "$fdotfile" ]; then
+    fdotfile="$(ls | grep '.*\.dot$')"
+    num_dotfiles=$(echo -n "$fdotfile" | wc -l)
+    if [ $num_dotfiles -eq 1 ]; then
+        echo "Automatic DOT file found, '$fdotfile'."
+    elif [ $num_dotfiles -le 0 ]; then
+        echo "Error: no automatic DOT file found."
+        exit 1
+    elif [ $num_dotfiles -gt 1 ]; then
+        echo "Error: too many DOT files found, '$fdotfile'."
+        exit 1
+    fi
+elif [ ! -e "$fdotfile" ]; then
+    echo "Error: DOT file '$fdotfile' does not exists."
+    exit 1
 fi
 
-#if [ ! -z $DOTFILE ]; then
-#    dot -Txdot $DOTFILE | dot2tex > graph.tex
-#fi
+# Commands (compile) 
+dir_dotfile="$(dirname $fdotfile)"
+dotfile="$(basename $fdotfile)"
+base_dotfile="${dotfile%.*}"
+
+# Change to file directory
+pushd .
+cd "$dir_dotfile"
+
+# Run
+if [ $tex -eq 0 ]; then
+    out_dotfile="$base_dotfile.png"
+    dot_cmd="dot -Tpng $dotfile -o $out_dotfile"
+    view_cmd="gpicview $out_dotfile"
+    eval "$dot_cmd"
+    eval "$view_cmd & disown"
+elif [ $tex -eq 1 ]; then
+    out_dotfile="$base_dotfile.tex"
+    dot_cmd="dot -Txdot $dotfile | dot2tex > $out_dotfile"
+    eval "$dot_cmd"
+fi
+
+# Change to initial directory
+popd
+
+unset tex fdotfile num_dotfiles dotfile base_dotfile dir_dotfile out_dotfile dot_cmd view_cmd
+exit 0
 
diff --git a/bin/compile_latex b/bin/compile_latex
--- a/bin/compile_latex
+++ b/bin/compile_latex
@@ -6,12 +6,12 @@ usage()
     echo "Usage: $(basename $0) [--help] [--bibtex] [--clean] [--pdfpc] [--workdir \"WORDIR\"] [--file \"TeXFILE\"]"
     echo
     echo "Compile a LaTeX file into PDF format."
+    echo
     echo "If a LaTeX file is not provided, current directory is searched for one."
     echo "Default working directory is 'build'."
     echo "To remove working directory after compiling, enable the 'clean' option."
     echo "To run bibTeX enable the 'bibtex' option."
     echo "To view as Beamer presentation with pdfpc, enable 'pc' option."
-    echo "All other arguments are passed directly to pdfpc command line."
     echo
 }
 
@@ -19,9 +19,9 @@ usage()
 bibtex=0
 clean=0
 pdfpc=0
-pdfpc_opts=
 workdir="build"
-ftexfile=
+texffile=
+filext=".tex"
 
 # Get command line options 
 while [ "$1" ]; do 
@@ -38,94 +38,76 @@ while [ "$1" ]; do
         clean=1
         shift 1
         ;;
-        -w | --workdir)
-        workdir="$2"
-        shift 2
-        ;;
         -p | --pdfpc)
         pdfpc=1
         shift 1
         ;;
+        -w | --workdir)
+        workdir="$2"
+        shift 2
+        ;;
         -f | --file)
-        ftexfile="$2"
+        texffile="$2"
         shift 2
         ;;
         *)
-        if [ $pdfpc -eq 1 ]; then
-            pdfpc_opts+="$@"
-            shift ${#@}
-        else
-            echo "Error: invalid command line option, $1"
-            usage
-            exit 1
-        fi
+        echo "Error: invalid command line option, $1"
+        usage
+        exit 1
         ;;
     esac
 done
 
 # Validate
-if [ -z "$ftexfile" ]; then
-    ftexfile="$(ls | grep '.*\.tex$')"
-    num_texfiles=$(echo -n "$ftexfile" | wc -l)
-    if [ $num_texfiles -eq 1 ]; then
-        echo "Automatic TeX file found, '$ftexfile'."
-    elif [ $num_texfiles -le 0 ]; then
-        echo "Error: no automatic TeX file found."
-        exit 1
-    elif [ $num_texfiles -gt 1 ]; then
-        echo "Error: too many TeX files found, '$ftexfile'."
-        exit 1
-    fi
-elif [ ! -e "$ftexfile" ]; then
-    echo "Error: TeX file '$texfile' does not exists."
+if [ -z "$texffile" ]; then
+    . common_utils
+    find_file_ext "$filext" 
+    [ $? -ne 0 ] && exit 1
+    texffile="$file_list"
+elif [ ! -e "$texffile" ]; then
+    echo "Error: file '$texffile' does not exists."
     exit 1
 fi
 
 # Commands (compile and view) 
-dir_texfile="$(dirname $ftexfile)"
-texfile="$(basename $ftexfile)"
-base_texfile="${texfile%.*}"
-pdf_texfile="$base_texfile.pdf"
+texdir="$(dirname $texffile)"
+texfile="$(basename $texffile)"
+texbase="${texfile%.*}"
+texpdf="$texbase.pdf"
 pdflatex_cmd="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=$workdir $texfile"
-bibtex_cmd="bibtex $workdir/$base_texfile"
+bibtex_cmd="bibtex $workdir/$texbase"
 
 # Change to file directory
-pushd .
-cd "$dir_texfile"
+pushd . > /dev/null 2>&1
+cd "$texdir"
 
 [ ! -d "$workdir" ] && mkdir "$workdir"
 
 # Run
-eval "$pdflatex_cmd"
-if [ -e "$workdir/$pdf_texfile" ]; then 
-    if [ $bibtex -ge 1 ]; then
-        eval "$bibtex_cmd"
-        eval "$pdflatex_cmd"
-        eval "$pdflatex_cmd"
-    fi
-
-    # View
-    if [ $clean -ge 1 ]; then
-        mv "$workdir/$pdf_texfile" "$pdf_texfile"
-        rm -r "$workdir"
-        if [ $pdfpc -eq 0 ]; then
-            view_cmd="evince $pdf_texfile"
-        else
-            view_cmd="pdfpc $pdfpc_opts $pdf_texfile"
-        fi
-    else
-        if [ $pdfpc -eq 0 ]; then
-            view_cmd="evince $workdir/$pdf_texfile"
-        else
-            view_cmd="pdfpc $pdfpc_opts $workdir/$pdf_texfile"
-        fi
-    fi
-    eval "$view_cmd & disown"
+$pdflatex_cmd
+[ $? -ne 0 ] && exit 1
+if [ $bibtex -ge 1 ]; then
+    $bibtex_cmd
+    $pdflatex_cmd
+    $pdflatex_cmd
 fi
 
-# Change to initial directory
-popd
+# View
+if [ $clean -eq 0 ]; then
+    texpdf="$workdir/$texpdf"
+else
+    mv "$workdir/$texpdf" "$texpdf"
+    rm -r "$workdir"
+fi
+if [ $pdfpc -eq 0 ]; then
+    view_cmd="evince $texpdf"
+else
+    view_cmd="pdfpc $texpdf"
+fi
+$view_cmd & disown
 
-unset bibtex workdir pdfpc pdfpc_opts ftexfile num_texfiles texfile base_texfile dir_texfile pdf_texfile pdflatex_cmd bibtex_cmd view_cmd
+# Change to initial directory
+popd > /dev/null 2>&1
+
 exit 0
 
diff --git a/bin/compile_sas b/bin/compile_sas
--- a/bin/compile_sas
+++ b/bin/compile_sas
@@ -1,47 +1,65 @@
 #!/bin/bash 
 
-# Usage information
-while [ $1 ]; do 
-    case $1 in 
+usage()
+{
+    echo
+    echo "Usage: $(basename $0) [--help] [--file \"SASFILE\"] [SASOPT1] [SASOPTION2] ..."
+    echo
+    echo "Run SAS script."
+    echo
+    echo "If a SAS file is not provided, current directory is searched for one."
+    echo "All other arguments are passed directly to SAS command line."
+    echo
+}
+
+# Default options
+sasffile=
+sasopts=
+filext=".sas"
+
+# Get command line options
+while [ "$1" ]; do 
+    case "$1" in 
         -h | --help)
-        echo "Usage: $(basename $0) [--help] [--file SASfile]"
-        echo
-        echo "If a SAS file is not provided, current directory is searched for one."
-        echo "All other arguments are passed directly to SAS command line."
+        usage
         exit 0
         ;;
         -f | --file)
-        SASFILE=$2
+        sasffile="$2"
         shift 2
         ;;
         *)
-        SASOPTS+="$SASOPTS $1"
+        sasopts+="$sasopts $1"
         shift 1
         ;;
     esac
 done
 
-# Validate SAS file
-if [[ -z $SASFILE ]]; then
-    SASFILE=`ls | grep ".*\.sas$"`
-    NUMFILES=`ls | grep ".*\.sas$" | wc -l`
-    if [[ $NUMFILES -eq 0 ]]; then
-        echo "Warning: no automatic SAS file found, '$SASFILE'."
-        exit 1
-    elif [[ $NUMFILES -gt 1 ]]; then
-        echo "Error: too many SAS files found, '$SASFILE'."
-        exit 1
-    else
-        echo "Automatic SAS file found, '$SASFILE'."
-    fi
-fi
-if [[ ! -e $SASFILE ]]; then
-    echo "Error: SAS file does not exists, '$SASFILE'."
+# Validate
+if [ -z "$sasffile" ]; then
+    . common_utils
+    find_file_ext "$filext" 
+    [ $? -ne 0 ] && exit 1
+    sasffile="$file_list"
+elif [ ! -e "$sasffile" ]; then
+    echo "Error: file '$sasffile' does not exists."
     exit 1
 fi
 
-# Run commands
-sas -nonews $SASOPTS $SASFILE
+# Commands (compile) 
+sasdir="$(dirname $sasffile)"
+sasfile="$(basename $sasffile)"
+sas_cmd="sas -nonews $sasopts $sasfile"
 
-unset SASFILE NUMFILES
+# Change to file directory
+pushd . > /dev/null 2>&1
+cd "$sasdir"
+
+# Run
+$sas_cmd
+
+# Change to initial directory
+popd > /dev/null 2>&1
+
+exit 0
 
diff --git a/bin/count_source_files b/bin/count_source_files
--- a/bin/count_source_files
+++ b/bin/count_source_files
@@ -3,12 +3,20 @@
 usage()
 {
     echo
-    echo "Usage: $(basename $0) [--help] [--recursive] [--dir \"DIR\"] [\".EXT1\"] [\".EXT2\"] ..."
+    echo "Usage: $(basename $0) [--help] [--recursive] [--workdir \"WORKDIR\"] \".EXT1\" [\".EXT2\"] ..."
+    echo
+    echo "Count files that match given extension."
+    echo
+    echo "Default working directory is current directory."
+    echo "Default is to not recurse directories."
+    echo "Hidden files are ignored."
     echo
 }
 
 # Default options
-recursive=1
+recursive=
+workdir="."
+filext=()
 
 # Get command line options 
 while [ "$1" ]; do 
@@ -18,22 +26,44 @@ while [ "$1" ]; do
         exit 0
         ;;
         -r | --recursive)
-        recursive=1
+        recursive="-R"
+        shift 1
+        ;;
+        -w | --workdir)
+        workdir="$2"
+        shift 2
+        ;; 
+        *)
+        filext+=("$(echo "$1" | sed 's/\./\\\./g')")
         shift 1
         ;;
     esac
 done
 
-DIR=$1
-
-if [ -z $DIR ]; then
-    echo "ERROR! need to provide a directory to search recursively for C++ files."
-    exit 0
+# Validate
+if [ ! -d $workdir ]; then
+    echo "Error: working directory does not exists."
+    exit 1
 fi
+
+if [ ${#filext[@]} -eq 0 ]; then
+    echo "Error: no file extensions were provided."
+    exit 1
+fi
+
+# Change to file directory
+pushd . > /dev/null 2>&1
+cd "$workdir"
 
 # List files recursively, ignore hidden files
 # Filter source files and count
-NUMFILES=`ls -R "$DIR" | grep -E '(\.cpp|\.h)$' | wc -l`
+file_regex=$(IFS="|"; echo "${filext[*]}")
+file_list=($(ls -1 "$recursive" | grep -E ".+($file_regex)$"))
+num_files=${#file_list[@]}
+echo "Number of matched files: $num_files"
 
-echo "Number of C++ files: $NUMFILES"
+# Change to initial directory
+popd . > /dev/null 2>&1
+
+exit 0
 
