fixed compile ASCIIDoc/TeX, added prog Perl scripts

diff --git a/bin/compile_asciidoc b/bin/compile_asciidoc
--- a/bin/compile_asciidoc
+++ b/bin/compile_asciidoc
@@ -3,16 +3,21 @@
 usage()
 {
     echo
-    echo "Usage: $(basename $0) [--help] [--file \"ADFILE\"]"
+    echo "Usage: $(basename $0) [--help] [--article] [--book] [--docbook] [--file \"ADFILE\"]"
     echo
+    echo "Compile an ASCIIDoc file into PDF format."
     echo "If an ASCIIDoc file is not provided, current directory is searched for one."
-    echo "All other arguments are ignored."
+    echo
+    echo "Type of output file:"
+    echo " 0 -> article (default)"
+    echo " 1 -> book"
+    echo " 2 -> docbook"
     echo
 }
 
-
 # Default options
-adfile=
+type_id=0
+fadfile=
 
 # Get command line options 
 while [ "$1" ]; do 
@@ -21,8 +26,20 @@ while [ "$1" ]; do
         usage
         exit 0
         ;;
+        -a | --article)
+        type_id=0
+        shift 1
+        ;;
+        -b | --book)
+        type_id=1
+        shift 1
+        ;;
+        -d | --docbook)
+        type_id=2
+        shift 1
+        ;;
         -f | --file)
-        adfile="$2"
+        fadfile="$2"
         shift 2
         ;;
         *)
@@ -34,37 +51,62 @@ while [ "$1" ]; do
 done
      
 # Validate
-if [ -z "$adfile" ]; then
-    adfile="$(ls | grep '.*\.asciidoc$')"
-    num_adfiles=$(ls | grep '.*\.asciidoc$' | wc -l)
-    if [ $num_adfiles -le 0 ]; then
-        echo "Error: no automatic ASCIIDoc file found."
-        exit 1
-    elif [ $num_adfiles -gt 1 ]; then
-        echo "Error: too many ASCIIDoc files found, '$adfile'."
-        exit 1
-    else
-        echo "Automatic ASCIIDoc file found, '$adfile'."
-    fi
-elif [ ! -e "$adfile" ]; then
-    echo "Error: ASCIIDoc file '$adfile' does not exists."
+if [ $type_id -lt 0 ] || [ $type_id -gt 2 ]; then
+    echo "Error: invalid value for compilation type."
     exit 1
 fi
 
-# Compiling commands
-base_adfile="${adfile%.*}"
-#ad_cmd="asciidoc -b docbook $adfile"
-ad_cmd="a2x -d article -f pdf $adfile"
-dblatex_cmd="dblatex $base_adfile.xml -T simple"
+if [ -z "$fadfile" ]; then
+    fadfile="$(ls | grep '.*\.asciidoc$')"
+    num_adfiles=$(echo -n "$fadfile" | wc -l)
+    if [ $num_adfiles -eq 1 ]; then
+        echo "Automatic ASCIIDoc file found, '$fadfile'."
+    elif [ $num_adfiles -le 0 ]; then
+        echo "Error: no automatic ASCIIDoc file found."
+        exit 1
+    elif [ $num_adfiles -gt 1 ]; then
+        echo "Error: too many ASCIIDoc files found, '$fadfile'."
+        exit 1
+    fi
+elif [ ! -e "$fadfile" ]; then
+    echo "Error: ASCIIDoc file '$fadfile' does not exists."
+    exit 1
+fi
 
-# Viewer commands
-view_cmd="evince $base_adfile.pdf"
+# Commands (compile and view)
+dir_adfile="$(dirname $fadfile)"
+adfile="$(basename $fadfile)"
+base_adfile="${adfile%.*}"
+pdf_adfile="$base_adfile.pdf"
+xml_adfile="$base_adfile.xml"
+dblatex_cmd="dblatex $xml_adfile -T simple"
+view_cmd="evince $pdf_adfile"
+
+case $type_id in
+    0) ad_cmd="a2x -d article -f pdf $adfile" ;;
+    1) ad_cmd="a2x -d book -f pdf $adfile" ;;
+    2) ad_cmd="asciidoc -b docbook $adfile" ;;
+esac
+
+# Change to file directory
+pushd .
+cd "$dir_adfile"
 
 # Run
 eval "$ad_cmd"
-#eval "$dblatex_cmd" && rm "$base_adfile.xml"
-eval "$view_cmd & disown"
+if [ -e "$xml_adfile" ]; then
+    eval "$dblatex_cmd"
+    rm "$xml_adfile"
+fi
 
-unset adfile num_adfiles base_adfile ad_cmd dblatex_cmd view_cmd
+# View
+if [ -e "$pdf_adfile" ]; then
+    eval "$view_cmd & disown"
+fi
+
+# Change to initial directory
+popd
+
+unset type_id fadfile num_adfiles adfile dir_adfile base_adfile pdf_adfile xml_adfile ad_cmd dblatex_cmd view_cmd
 exit 0
 
diff --git a/bin/compile_latex b/bin/compile_latex
--- a/bin/compile_latex
+++ b/bin/compile_latex
@@ -1,73 +1,131 @@
 #!/bin/bash 
 
-# Usage information
-while [ $1 ]; do 
-    case $1 in 
+usage()
+{
+    echo
+    echo "Usage: $(basename $0) [--help] [--bibtex] [--clean] [--pdfpc] [--workdir \"WORDIR\"] [--file \"TeXFILE\"]"
+    echo
+    echo "Compile a LaTeX file into PDF format."
+    echo "If a LaTeX file is not provided, current directory is searched for one."
+    echo "Default working directory is 'build'."
+    echo "To remove working directory after compiling, enable the 'clean' option."
+    echo "To run bibTeX enable the 'bibtex' option."
+    echo "To view as Beamer presentation with pdfpc, enable 'pc' option."
+    echo "All other arguments are passed directly to pdfpc command line."
+    echo
+}
+
+# Default options
+bibtex=0
+clean=0
+pdfpc=0
+pdfpc_opts=
+workdir="build"
+ftexfile=
+
+# Get command line options 
+while [ "$1" ]; do 
+    case "$1" in 
         -h | --help)
-        echo "Usage: $(basename $0) [--help] [--nobib] [--outdir example] [--file TeXfile]"
-        echo
-        echo "If a LaTeX file is not provided, current directory is searched for one."
-        echo "Default output directory is 'build'."
-        echo "All other arguments are ignored."
-        echo "The 'nobib' does not runs bibTeX."
+        usage
         exit 0
         ;;
-        -n | --nobib)
-        NOBIB=1
+        -b | --bibtex)
+        bibtex=1
         shift 1
         ;;
-        -o | --outdir)
-        OUTDIR=$2
+        -c | --clean)
+        clean=1
+        shift 1
+        ;;
+        -w | --workdir)
+        workdir="$2"
         shift 2
         ;;
+        -p | --pdfpc)
+        pdfpc=1
+        shift 1
+        ;;
         -f | --file)
-        TEXFILE=$2
+        ftexfile="$2"
         shift 2
         ;;
         *)
-        echo "Invalid argument: $1"
-        exit 0
+        if [ $pdfpc -eq 1 ]; then
+            pdfpc_opts+="$@"
+            shift ${#@}
+        else
+            echo "Error: invalid command line option, $1"
+            usage
+            exit 1
+        fi
         ;;
     esac
 done
 
-# Validate TeX file
-if [[ -z $TEXFILE ]]; then
-    TEXFILE=`ls | grep ".*\.tex$"`
-    NUMFILES=`ls | grep ".*\.tex$" | wc -l`
-    if [[ $NUMFILES -eq 0 ]]; then
-        echo "Warning: no automatic TeX file found, '$TEXFILE'."
+# Validate
+if [ -z "$ftexfile" ]; then
+    ftexfile="$(ls | grep '.*\.tex$')"
+    num_texfiles=$(echo -n "$ftexfile" | wc -l)
+    if [ $num_texfiles -eq 1 ]; then
+        echo "Automatic TeX file found, '$ftexfile'."
+    elif [ $num_texfiles -le 0 ]; then
+        echo "Error: no automatic TeX file found."
         exit 1
-    elif [[ $NUMFILES -gt 1 ]]; then
-        echo "Error: too many TeX files found, '$TEXFILE'."
+    elif [ $num_texfiles -gt 1 ]; then
+        echo "Error: too many TeX files found, '$ftexfile'."
         exit 1
-    else
-        echo "Automatic TeX file found, '$TEXFILE'."
     fi
-fi
-if [[ ! -e $TEXFILE ]]; then
-    echo "Error: TeX file does not exists, '$TEXFILE'."
+elif [ ! -e "$ftexfile" ]; then
+    echo "Error: TeX file '$texfile' does not exists."
     exit 1
 fi
 
-# Validate output directory
-[[ -z $OUTDIR ]] && OUTDIR="build"
-[[ ! -d $OUTDIR ]] && mkdir $OUTDIR
+# Commands (compile and view) 
+dir_texfile="$(dirname $ftexfile)"
+texfile="$(basename $ftexfile)"
+base_texfile="${texfile%.*}"
+pdf_texfile="$base_texfile.pdf"
+pdflatex_cmd="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=$workdir $texfile"
+bibtex_cmd="bibtex $workdir/$base_texfile"
 
-# Define commands
-BASEFILE=${TEXFILE%.*}
-PDFLATEX_CMD="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=$OUTDIR $TEXFILE"
-BIBTEX_CMD="bibtex $OUTDIR/$BASEFILE"
-PDFVIEW_CMD="evince $OUTDIR/$BASEFILE.pdf"
+# Change to file directory
+pushd .
+cd "$dir_texfile"
 
-# Run commands
-if [[ -z $NOBIB ]]; then
-    $PDFLATEX_CMD
-    $BIBTEX_CMD
+[ ! -d "$workdir" ] && mkdir "$workdir"
+
+# Run
+eval "$pdflatex_cmd"
+if [ -e "$workdir/$pdf_texfile" ]; then 
+    if [ $bibtex -ge 1 ]; then
+        eval "$bibtex_cmd"
+        eval "$pdflatex_cmd"
+        eval "$pdflatex_cmd"
+    fi
+
+    # View
+    if [ $clean -ge 1 ]; then
+        mv "$workdir/$pdf_texfile" "$pdf_texfile"
+        rm -r "$workdir"
+        if [ $pdfpc -eq 0 ]; then
+            view_cmd="evince $pdf_texfile"
+        else
+            view_cmd="pdfpc $pdfpc_opts $pdf_texfile"
+        fi
+    else
+        if [ $pdfpc -eq 0 ]; then
+            view_cmd="evince $workdir/$pdf_texfile"
+        else
+            view_cmd="pdfpc $pdfpc_opts $workdir/$pdf_texfile"
+        fi
+    fi
+    eval "$view_cmd & disown"
 fi
-$PDFLATEX_CMD
-$PDFLATEX_CMD
-$PDFVIEW_CMD & disown
 
-unset TEXFILE NUMFILES NOBIB OUTDIR BASEFILE PDFLATEX_CMD BIBTEX_CMD PDFVIEW_CMD
+# Change to initial directory
+popd
+
+unset bibtex workdir pdfpc pdfpc_opts ftexfile num_texfiles texfile base_texfile dir_texfile pdf_texfile pdflatex_cmd bibtex_cmd view_cmd
+exit 0
 
