more POSIX related changes

diff --git a/bin/error_utils b/bin/error_utils
--- a/bin/error_utils
+++ b/bin/error_utils
@@ -1,26 +1,36 @@
-#!/bin/bash
+#!/bin/sh
 
 # Print error message, exits if exit code provided
+#
 # Inputs: "error message" [exit code]
 # Outputs: N/A
 # Usage: error_msg "file does not exists" 1
 error_msg()
 {
-    declare -r errcolor="\033[01;31m" # red
-    declare -r offcolor="\033[00m" # off
-    echo -e "${errcolor}ERROR:${offcolor} $1"
-    [[ $2 =~ ^[0-9]+$ ]] && exit $2
+    errcolor="\033[01;31m" # red
+    offcolor="\033[00m" # off
+    printf "%b\n" "${errcolor}ERROR:${offcolor} $1"
+    case ${2#[-+]} in
+        *[!0-9]* | "") ;;
+        *) exit $2 ;;
+    esac
+    unset errcolor offcolor
 }
 
 # Print warning message, exits if error code provided
+#
 # Inputs: "warning message" [exit code]
 # Outputs: N/A
 # Usage: warn_msg "value out of range" 1
 warn_msg()
 {
-    declare -r errcolor="\033[01;31m" # red
-    declare -r offcolor="\033[00m" # off
-    echo -e "${errcolor}WARNING:${offcolor} $1"
-    [[ $2 =~ ^[0-9]+$ ]] && exit $2
+    errcolor="\033[01;31m" # red
+    offcolor="\033[00m" # off
+    printf "%b\n" "${errcolor}WARNING:${offcolor} $1"
+    case ${2#[-+]} in
+        *[!0-9]* | "") ;;
+        *) exit $2 ;;
+    esac
+    unset errcolor offcolor
 }
 
diff --git a/bin/matlab_cli b/bin/matlab_cli
--- a/bin/matlab_cli
+++ b/bin/matlab_cli
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/bin/sh
 
-. "$HOME/bin/error_utils"
+errmsg="\033[01;31mERROR\033[00m"
+warnmsg="\033[01;33mWARNING\033[00m"
 
 usage()
 {
@@ -17,19 +18,15 @@ _EOF_
 # Default options
 deskcmd="-nodesktop -nosplash"
 jvmcmd="-nodisplay -nojvm"
-runcmd=
+runcmd=""
 
 # Get command line options
 while [ "$1" ]; do
     case "$1" in
-        -h | --help)
-            usage
-            exit 0
-            ;;
-        -j | --jvm)
-            jvmcmd=
-            shift
-            ;;
+        -h | --help) usage
+            exit 0 ;;
+        -j | --jvm) jvmcmd=""
+            shift ;;
         -r | --run)
             if [ "${2##*.}" = "m" ]; then
                 # Script
@@ -38,17 +35,13 @@ while [ "$1" ]; do
                 # Command
                 runcmd="-r \"try, $2, catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end\""
             fi
-            shift 2
-            ;;
-        *)
-            usage
-            error_msg "invalid command line option, $1" 1
-            ;;
+            shift 2 ;;
+        *) usage
+            printf "%b\n" "$errmsg: invalid command line option, $1"
+            exit 1 ;;
     esac
 done
 
 # Run
 matlab "$deskcmd" "$jvmcmd" "$runcmd"
-
-exit 0
 
