enable HorizTwoFingerScroll for laptops only

diff --git a/bin/lightdm_display_setup b/bin/lightdm_display_setup
--- a/bin/lightdm_display_setup
+++ b/bin/lightdm_display_setup
@@ -2,6 +2,7 @@
 
 # This script is executed during LightDM X11 display at startup.
 # Used in: /usr/share/lightdm/lightdm.conf.d/20-lubuntu.conf
+# If an error occurs here, LightDM X11 may fail to start. 
 
 # Set display to main monitor only
 which xrandr > /dev/null 2>&1
@@ -11,14 +12,17 @@ if [ $? -eq 0 ]; then
     fi
 fi
 
-# Enable horizontal two finger scroll for Synaptic touchpad
-# Creates error in MATLAB, so disable it
-#which synclient > /dev/null 2>&1
-#if [ $? -eq 0 ]; then
-#    if [ $(synclient -l | awk -F'=' '/HorizTwoFingerScroll/ { print $2 }') -eq 0 ]; then
-#        synclient HorizTwoFingerScroll=1
-#    fi
-#fi
+# For laptops, enable horizontal two finger scroll (Synaptic touchpad)
+# NOTE: Creates error in MATLAB
+laptop-detect
+if [ $? -eq 0 ]; then
+    which synclient > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        if [ $(synclient -l | awk -F'=' '/HorizTwoFingerScroll/ { print $2 }') -eq 0 ]; then
+            synclient HorizTwoFingerScroll=1
+        fi
+    fi
+fi
 
 # Enable numlock
 which numlockx > /dev/null 2>&1
