changes to nvidiax after upgrade and vim with clear

diff --git a/nvidiax b/nvidiax
--- a/nvidiax
+++ b/nvidiax
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# X11 NVIDIA configuration file, do not change
-declare -r x11_nvidia_file="/usr/share/X11/xorg.conf.d/52-nvidia.conf"
-declare -r default_perf_level=3
+# DO NOT CHANGE
+# X11 NVIDIA configuration file
+declare -r x11_nvidia_file="/etc/bumblebee/xorg.conf.nvidia"
 
 usage()
 {
@@ -24,14 +24,14 @@ usage()
     echo
     echo "GPU launcher tools:"
     echo " 0 -> none"
-    echo " 1 -> primusrun"
-    echo " 2 -> optirun (default)"
+    echo " 1 -> primusrun (default) (for OpenGL apps)"
+    echo " 2 -> optirun"
     echo
 }
 
 # Default options
-launch_tool=2
-perf_level=$default_perf_level
+launch_tool=1
+perf_level=3
 perf_level_changed=0
 app=
 
@@ -51,9 +51,6 @@ while [ "$1" ]; do
         shift 2
         ;;
         -r | --run)
-        #shift 1
-        #app="$@"
-        #shift $# 
         app="$2"
         shift 2 
         ;;
@@ -84,9 +81,10 @@ if [ $launch_tool -lt 0 ] || [ $launch_tool -gt 2 ]; then
 fi
 
 if [ $launch_tool -gt 0 ]; then
-    if [ ! -e "$x11_nvidia_file" ]; then
-        echo "Error: X11 NVIDIA configuration file '$x11_nvidia_file' does not exists."
-        exit 1
+    # Check that NVIDIA modules are not loaded/used by other applications 
+    if [ $(lsmod | grep -c nvidia) -gt 0 ]; then
+        echo "Warning: Please close all applications using NVIDIA modules...exiting."
+        exit 0
     fi
 
     if [ $perf_level -lt 1 ] || [ $perf_level -gt 3 ]; then
@@ -94,11 +92,14 @@ if [ $launch_tool -gt 0 ]; then
         exit 1 
     fi
 
-    # Check that NVIDIA modules are not loaded
-    if [ $(lsmod | grep -c nvidia) -gt 0 ]; then
-        echo "Warning: Please close all applications using NVIDIA modules...exiting."
-        exit 0
+    if [ ! -e "$x11_nvidia_file" ]; then
+        echo "Error: X11 NVIDIA configuration file '$x11_nvidia_file' does not exists."
+        exit 1
     fi
+
+    # Get current performance level in X11 NVIDIA configuration file
+    default_perf_level=$(grep "RegistryDwords" "$x11_nvidia_file" | grep -o 'PowerMizerLevel=0x[[:digit:]]' | awk -F'=0x' '{ print $2 }')
+    echo "Current NVIDIA GPU performance level is $default_perf_level."
 
     # Set performance level in X11 NVIDIA configuration file
     if [ $perf_level -ne $default_perf_level ]; then
@@ -113,7 +114,7 @@ if [ $launch_tool -gt 0 ]; then
     fi
 fi
 
-# Select launcher tool 
+# Select launcher tool
 if [ $launch_tool -eq 0 ]; then
     cmd="$app"
 elif [ $launch_tool -eq 1 ]; then
@@ -132,5 +133,5 @@ if [ $perf_level_changed -eq 1 ]; then
     perf_level_changed=0
 fi
 
-unset perf_level perf_level_changed launch_tool app cmd
+unset perf_level default_perf_level perf_level_changed launch_tool app cmd
 
